
envSecrets:
  dbCredentials:
    existingSecret: "db-secret"
    dbEncryptionKey: "db-encryption-key"
    dbUrlKey: "db-url"
    dbPasswordKey: "mysql-root-password"
    dbUserPasswordKey: "mysql-password"
